sever:
  port: 8000

zuul:
  prefix: /api
  routes:
    bank:
      path: /bank/**
      url: http://localhost:8082/bank
    jswish:
      path: /jswish/**
      url: http://localhost:8081/jswish

endpoints:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false